---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  remote_user: user
  become: true

  roles:
      - common
      - mysql
      - nginx
      - php
      - wordpress
