---
- name: Download WordPress
  ansible.builtin.get_url:
    url: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /srv/wordpress-{{ wp_version }}.tar.gz
    mode: "0644"

- name: Extract archive
  ansible.builtin.unarchive:
    src: /srv/wordpress-{{ wp_version }}.tar.gz
    dest: /srv
    remote_src: true

- name: Add group "wordpress"
  ansible.builtin.group:
    name: wordpress

- name: Add user "wordpress"
  ansible.builtin.user:
    name: wordpress
    group: wordpress
    home: /srv/wordpress/

- name: Fetch random salts for WordPress config
  ansible.builtin.uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: true
  register: wp_salt

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    state: present

- name: Copy WordPress config file
  ansible.builtin.template:
    src: wp-config.php
    dest: /srv/wordpress/
    owner: wordpress
    group: wordpress
    mode: "0640"

- name: Change ownership of WordPress installation
  ansible.builtin.file:
    path: /srv/wordpress/
    owner: wordpress
    group: wordpress
    state: directory
    recurse: true
    setype: httpd_sys_content_t

- name: Start php-fpm Service
  ansible.builtin.service:
    name: php-fpm
    state: started
