---
- name: Install Mysql package
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python3-mysql

- name: Create Mysql configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    group: root
    owner: root
    mode: "0644"
  notify:
    - Restart mysql

- name: Start Mysql Service
  ansible.builtin.service:
    name: mysqld
    state: started
